<?php
/**
 * Account
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace YNAB\Model;

use \ArrayAccess;
use \YNAB\ObjectSerializer;

/**
 * Account Class Doc Comment
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Account implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Account';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'name' => 'string',
        'type' => '\YNAB\Model\AccountType',
        'on_budget' => 'bool',
        'closed' => 'bool',
        'note' => 'string',
        'balance' => 'int',
        'cleared_balance' => 'int',
        'uncleared_balance' => 'int',
        'transfer_payee_id' => 'string',
        'direct_import_linked' => 'bool',
        'direct_import_in_error' => 'bool',
        'last_reconciled_at' => '\DateTime',
        'debt_original_balance' => 'int',
        'debt_interest_rates' => '\YNAB\Model\LoanAccountPeriodicValue',
        'debt_minimum_payments' => '\YNAB\Model\LoanAccountPeriodicValue',
        'debt_escrow_amounts' => '\YNAB\Model\LoanAccountPeriodicValue',
        'deleted' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'uuid',
        'name' => null,
        'type' => null,
        'on_budget' => null,
        'closed' => null,
        'note' => null,
        'balance' => 'int64',
        'cleared_balance' => 'int64',
        'uncleared_balance' => 'int64',
        'transfer_payee_id' => 'uuid',
        'direct_import_linked' => null,
        'direct_import_in_error' => null,
        'last_reconciled_at' => 'date-time',
        'debt_original_balance' => 'int64',
        'debt_interest_rates' => null,
        'debt_minimum_payments' => null,
        'debt_escrow_amounts' => null,
        'deleted' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'type' => 'type',
        'on_budget' => 'on_budget',
        'closed' => 'closed',
        'note' => 'note',
        'balance' => 'balance',
        'cleared_balance' => 'cleared_balance',
        'uncleared_balance' => 'uncleared_balance',
        'transfer_payee_id' => 'transfer_payee_id',
        'direct_import_linked' => 'direct_import_linked',
        'direct_import_in_error' => 'direct_import_in_error',
        'last_reconciled_at' => 'last_reconciled_at',
        'debt_original_balance' => 'debt_original_balance',
        'debt_interest_rates' => 'debt_interest_rates',
        'debt_minimum_payments' => 'debt_minimum_payments',
        'debt_escrow_amounts' => 'debt_escrow_amounts',
        'deleted' => 'deleted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'type' => 'setType',
        'on_budget' => 'setOnBudget',
        'closed' => 'setClosed',
        'note' => 'setNote',
        'balance' => 'setBalance',
        'cleared_balance' => 'setClearedBalance',
        'uncleared_balance' => 'setUnclearedBalance',
        'transfer_payee_id' => 'setTransferPayeeId',
        'direct_import_linked' => 'setDirectImportLinked',
        'direct_import_in_error' => 'setDirectImportInError',
        'last_reconciled_at' => 'setLastReconciledAt',
        'debt_original_balance' => 'setDebtOriginalBalance',
        'debt_interest_rates' => 'setDebtInterestRates',
        'debt_minimum_payments' => 'setDebtMinimumPayments',
        'debt_escrow_amounts' => 'setDebtEscrowAmounts',
        'deleted' => 'setDeleted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'type' => 'getType',
        'on_budget' => 'getOnBudget',
        'closed' => 'getClosed',
        'note' => 'getNote',
        'balance' => 'getBalance',
        'cleared_balance' => 'getClearedBalance',
        'uncleared_balance' => 'getUnclearedBalance',
        'transfer_payee_id' => 'getTransferPayeeId',
        'direct_import_linked' => 'getDirectImportLinked',
        'direct_import_in_error' => 'getDirectImportInError',
        'last_reconciled_at' => 'getLastReconciledAt',
        'debt_original_balance' => 'getDebtOriginalBalance',
        'debt_interest_rates' => 'getDebtInterestRates',
        'debt_minimum_payments' => 'getDebtMinimumPayments',
        'debt_escrow_amounts' => 'getDebtEscrowAmounts',
        'deleted' => 'getDeleted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['on_budget'] = isset($data['on_budget']) ? $data['on_budget'] : null;
        $this->container['closed'] = isset($data['closed']) ? $data['closed'] : null;
        $this->container['note'] = isset($data['note']) ? $data['note'] : null;
        $this->container['balance'] = isset($data['balance']) ? $data['balance'] : null;
        $this->container['cleared_balance'] = isset($data['cleared_balance']) ? $data['cleared_balance'] : null;
        $this->container['uncleared_balance'] = isset($data['uncleared_balance']) ? $data['uncleared_balance'] : null;
        $this->container['transfer_payee_id'] = isset($data['transfer_payee_id']) ? $data['transfer_payee_id'] : null;
        $this->container['direct_import_linked'] = isset($data['direct_import_linked']) ? $data['direct_import_linked'] : null;
        $this->container['direct_import_in_error'] = isset($data['direct_import_in_error']) ? $data['direct_import_in_error'] : null;
        $this->container['last_reconciled_at'] = isset($data['last_reconciled_at']) ? $data['last_reconciled_at'] : null;
        $this->container['debt_original_balance'] = isset($data['debt_original_balance']) ? $data['debt_original_balance'] : null;
        $this->container['debt_interest_rates'] = isset($data['debt_interest_rates']) ? $data['debt_interest_rates'] : null;
        $this->container['debt_minimum_payments'] = isset($data['debt_minimum_payments']) ? $data['debt_minimum_payments'] : null;
        $this->container['debt_escrow_amounts'] = isset($data['debt_escrow_amounts']) ? $data['debt_escrow_amounts'] : null;
        $this->container['deleted'] = isset($data['deleted']) ? $data['deleted'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['on_budget'] === null) {
            $invalidProperties[] = "'on_budget' can't be null";
        }
        if ($this->container['closed'] === null) {
            $invalidProperties[] = "'closed' can't be null";
        }
        if ($this->container['balance'] === null) {
            $invalidProperties[] = "'balance' can't be null";
        }
        if ($this->container['cleared_balance'] === null) {
            $invalidProperties[] = "'cleared_balance' can't be null";
        }
        if ($this->container['uncleared_balance'] === null) {
            $invalidProperties[] = "'uncleared_balance' can't be null";
        }
        if ($this->container['transfer_payee_id'] === null) {
            $invalidProperties[] = "'transfer_payee_id' can't be null";
        }
        if ($this->container['deleted'] === null) {
            $invalidProperties[] = "'deleted' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \YNAB\Model\AccountType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \YNAB\Model\AccountType $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets on_budget
     *
     * @return bool
     */
    public function getOnBudget()
    {
        return $this->container['on_budget'];
    }

    /**
     * Sets on_budget
     *
     * @param bool $on_budget Whether this account is on budget or not
     *
     * @return $this
     */
    public function setOnBudget($on_budget)
    {
        $this->container['on_budget'] = $on_budget;

        return $this;
    }

    /**
     * Gets closed
     *
     * @return bool
     */
    public function getClosed()
    {
        return $this->container['closed'];
    }

    /**
     * Sets closed
     *
     * @param bool $closed Whether this account is closed or not
     *
     * @return $this
     */
    public function setClosed($closed)
    {
        $this->container['closed'] = $closed;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string $note note
     *
     * @return $this
     */
    public function setNote($note)
    {
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets balance
     *
     * @return int
     */
    public function getBalance()
    {
        return $this->container['balance'];
    }

    /**
     * Sets balance
     *
     * @param int $balance The current balance of the account in milliunits format
     *
     * @return $this
     */
    public function setBalance($balance)
    {
        $this->container['balance'] = $balance;

        return $this;
    }

    /**
     * Gets cleared_balance
     *
     * @return int
     */
    public function getClearedBalance()
    {
        return $this->container['cleared_balance'];
    }

    /**
     * Sets cleared_balance
     *
     * @param int $cleared_balance The current cleared balance of the account in milliunits format
     *
     * @return $this
     */
    public function setClearedBalance($cleared_balance)
    {
        $this->container['cleared_balance'] = $cleared_balance;

        return $this;
    }

    /**
     * Gets uncleared_balance
     *
     * @return int
     */
    public function getUnclearedBalance()
    {
        return $this->container['uncleared_balance'];
    }

    /**
     * Sets uncleared_balance
     *
     * @param int $uncleared_balance The current uncleared balance of the account in milliunits format
     *
     * @return $this
     */
    public function setUnclearedBalance($uncleared_balance)
    {
        $this->container['uncleared_balance'] = $uncleared_balance;

        return $this;
    }

    /**
     * Gets transfer_payee_id
     *
     * @return string
     */
    public function getTransferPayeeId()
    {
        return $this->container['transfer_payee_id'];
    }

    /**
     * Sets transfer_payee_id
     *
     * @param string $transfer_payee_id The payee id which should be used when transferring to this account
     *
     * @return $this
     */
    public function setTransferPayeeId($transfer_payee_id)
    {
        $this->container['transfer_payee_id'] = $transfer_payee_id;

        return $this;
    }

    /**
     * Gets direct_import_linked
     *
     * @return bool
     */
    public function getDirectImportLinked()
    {
        return $this->container['direct_import_linked'];
    }

    /**
     * Sets direct_import_linked
     *
     * @param bool $direct_import_linked Whether or not the account is linked to a financial institution for automatic transaction import.
     *
     * @return $this
     */
    public function setDirectImportLinked($direct_import_linked)
    {
        $this->container['direct_import_linked'] = $direct_import_linked;

        return $this;
    }

    /**
     * Gets direct_import_in_error
     *
     * @return bool
     */
    public function getDirectImportInError()
    {
        return $this->container['direct_import_in_error'];
    }

    /**
     * Sets direct_import_in_error
     *
     * @param bool $direct_import_in_error If an account linked to a financial institution (direct_import_linked=true) and the linked connection is not in a healthy state, this will be true.
     *
     * @return $this
     */
    public function setDirectImportInError($direct_import_in_error)
    {
        $this->container['direct_import_in_error'] = $direct_import_in_error;

        return $this;
    }

    /**
     * Gets last_reconciled_at
     *
     * @return \DateTime
     */
    public function getLastReconciledAt()
    {
        return $this->container['last_reconciled_at'];
    }

    /**
     * Sets last_reconciled_at
     *
     * @param \DateTime $last_reconciled_at A date/time specifying when the account was last reconciled.
     *
     * @return $this
     */
    public function setLastReconciledAt($last_reconciled_at)
    {
        $this->container['last_reconciled_at'] = $last_reconciled_at;

        return $this;
    }

    /**
     * Gets debt_original_balance
     *
     * @return int
     */
    public function getDebtOriginalBalance()
    {
        return $this->container['debt_original_balance'];
    }

    /**
     * Sets debt_original_balance
     *
     * @param int $debt_original_balance The original debt/loan account balance, specified in milliunits format.
     *
     * @return $this
     */
    public function setDebtOriginalBalance($debt_original_balance)
    {
        $this->container['debt_original_balance'] = $debt_original_balance;

        return $this;
    }

    /**
     * Gets debt_interest_rates
     *
     * @return \YNAB\Model\LoanAccountPeriodicValue
     */
    public function getDebtInterestRates()
    {
        return $this->container['debt_interest_rates'];
    }

    /**
     * Sets debt_interest_rates
     *
     * @param \YNAB\Model\LoanAccountPeriodicValue $debt_interest_rates debt_interest_rates
     *
     * @return $this
     */
    public function setDebtInterestRates($debt_interest_rates)
    {
        $this->container['debt_interest_rates'] = $debt_interest_rates;

        return $this;
    }

    /**
     * Gets debt_minimum_payments
     *
     * @return \YNAB\Model\LoanAccountPeriodicValue
     */
    public function getDebtMinimumPayments()
    {
        return $this->container['debt_minimum_payments'];
    }

    /**
     * Sets debt_minimum_payments
     *
     * @param \YNAB\Model\LoanAccountPeriodicValue $debt_minimum_payments debt_minimum_payments
     *
     * @return $this
     */
    public function setDebtMinimumPayments($debt_minimum_payments)
    {
        $this->container['debt_minimum_payments'] = $debt_minimum_payments;

        return $this;
    }

    /**
     * Gets debt_escrow_amounts
     *
     * @return \YNAB\Model\LoanAccountPeriodicValue
     */
    public function getDebtEscrowAmounts()
    {
        return $this->container['debt_escrow_amounts'];
    }

    /**
     * Sets debt_escrow_amounts
     *
     * @param \YNAB\Model\LoanAccountPeriodicValue $debt_escrow_amounts debt_escrow_amounts
     *
     * @return $this
     */
    public function setDebtEscrowAmounts($debt_escrow_amounts)
    {
        $this->container['debt_escrow_amounts'] = $debt_escrow_amounts;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool $deleted Whether or not the account has been deleted.  Deleted accounts will only be included in delta requests.
     *
     * @return $this
     */
    public function setDeleted($deleted)
    {
        $this->container['deleted'] = $deleted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
