<?php
/**
 * AccountType
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace YNAB\Model;
use \YNAB\ObjectSerializer;

/**
 * AccountType Class Doc Comment
 *
 * @category Class
 * @description The type of account
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountType
{
    /**
     * Possible values of this enum
     */
    const CHECKING = 'checking';
    const SAVINGS = 'savings';
    const CASH = 'cash';
    const CREDIT_CARD = 'creditCard';
    const LINE_OF_CREDIT = 'lineOfCredit';
    const OTHER_ASSET = 'otherAsset';
    const OTHER_LIABILITY = 'otherLiability';
    const MORTGAGE = 'mortgage';
    const AUTO_LOAN = 'autoLoan';
    const STUDENT_LOAN = 'studentLoan';
    const PERSONAL_LOAN = 'personalLoan';
    const MEDICAL_DEBT = 'medicalDebt';
    const OTHER_DEBT = 'otherDebt';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CHECKING
            self::SAVINGS
            self::CASH
            self::CREDIT_CARD
            self::LINE_OF_CREDIT
            self::OTHER_ASSET
            self::OTHER_LIABILITY
            self::MORTGAGE
            self::AUTO_LOAN
            self::STUDENT_LOAN
            self::PERSONAL_LOAN
            self::MEDICAL_DEBT
            self::OTHER_DEBT
        ];
    }
}
