<?php
/**
 * TransactionFlagColor
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace YNAB\Model;
use \YNAB\ObjectSerializer;

/**
 * TransactionFlagColor Class Doc Comment
 *
 * @category Class
 * @description The transaction flag
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionFlagColor
{
    /**
     * Possible values of this enum
     */
    const RED = 'red';
    const ORANGE = 'orange';
    const YELLOW = 'yellow';
    const GREEN = 'green';
    const BLUE = 'blue';
    const PURPLE = 'purple';
    const NULL = 'null';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RED
            self::ORANGE
            self::YELLOW
            self::GREEN
            self::BLUE
            self::PURPLE
            self::NULL
        ];
    }
}
