<?php
/**
 * AccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YNAB;

use PHPUnit\Framework\TestCase;

/**
 * AccountTest Class Doc Comment
 *
 * @category    Class
 * @description Account
 * @package     YNAB
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Account"
     */
    public function testAccount()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "on_budget"
     */
    public function testPropertyOnBudget()
    {
    }

    /**
     * Test attribute "closed"
     */
    public function testPropertyClosed()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "cleared_balance"
     */
    public function testPropertyClearedBalance()
    {
    }

    /**
     * Test attribute "uncleared_balance"
     */
    public function testPropertyUnclearedBalance()
    {
    }

    /**
     * Test attribute "transfer_payee_id"
     */
    public function testPropertyTransferPayeeId()
    {
    }

    /**
     * Test attribute "direct_import_linked"
     */
    public function testPropertyDirectImportLinked()
    {
    }

    /**
     * Test attribute "direct_import_in_error"
     */
    public function testPropertyDirectImportInError()
    {
    }

    /**
     * Test attribute "last_reconciled_at"
     */
    public function testPropertyLastReconciledAt()
    {
    }

    /**
     * Test attribute "debt_original_balance"
     */
    public function testPropertyDebtOriginalBalance()
    {
    }

    /**
     * Test attribute "debt_interest_rates"
     */
    public function testPropertyDebtInterestRates()
    {
    }

    /**
     * Test attribute "debt_minimum_payments"
     */
    public function testPropertyDebtMinimumPayments()
    {
    }

    /**
     * Test attribute "debt_escrow_amounts"
     */
    public function testPropertyDebtEscrowAmounts()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }
}
