<?php
/**
 * CategoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YNAB;

use PHPUnit\Framework\TestCase;

/**
 * CategoryTest Class Doc Comment
 *
 * @category    Class
 * @description Category
 * @package     YNAB
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CategoryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Category"
     */
    public function testCategory()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "category_group_id"
     */
    public function testPropertyCategoryGroupId()
    {
    }

    /**
     * Test attribute "category_group_name"
     */
    public function testPropertyCategoryGroupName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "hidden"
     */
    public function testPropertyHidden()
    {
    }

    /**
     * Test attribute "original_category_group_id"
     */
    public function testPropertyOriginalCategoryGroupId()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "budgeted"
     */
    public function testPropertyBudgeted()
    {
    }

    /**
     * Test attribute "activity"
     */
    public function testPropertyActivity()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "goal_type"
     */
    public function testPropertyGoalType()
    {
    }

    /**
     * Test attribute "goal_needs_whole_amount"
     */
    public function testPropertyGoalNeedsWholeAmount()
    {
    }

    /**
     * Test attribute "goal_day"
     */
    public function testPropertyGoalDay()
    {
    }

    /**
     * Test attribute "goal_cadence"
     */
    public function testPropertyGoalCadence()
    {
    }

    /**
     * Test attribute "goal_cadence_frequency"
     */
    public function testPropertyGoalCadenceFrequency()
    {
    }

    /**
     * Test attribute "goal_creation_month"
     */
    public function testPropertyGoalCreationMonth()
    {
    }

    /**
     * Test attribute "goal_target"
     */
    public function testPropertyGoalTarget()
    {
    }

    /**
     * Test attribute "goal_target_month"
     */
    public function testPropertyGoalTargetMonth()
    {
    }

    /**
     * Test attribute "goal_percentage_complete"
     */
    public function testPropertyGoalPercentageComplete()
    {
    }

    /**
     * Test attribute "goal_months_to_budget"
     */
    public function testPropertyGoalMonthsToBudget()
    {
    }

    /**
     * Test attribute "goal_under_funded"
     */
    public function testPropertyGoalUnderFunded()
    {
    }

    /**
     * Test attribute "goal_overall_funded"
     */
    public function testPropertyGoalOverallFunded()
    {
    }

    /**
     * Test attribute "goal_overall_left"
     */
    public function testPropertyGoalOverallLeft()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }
}
