<?php
/**
 * CurrencyFormatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YNAB;

use PHPUnit\Framework\TestCase;

/**
 * CurrencyFormatTest Class Doc Comment
 *
 * @category    Class
 * @description The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
 * @package     YNAB
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CurrencyFormatTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CurrencyFormat"
     */
    public function testCurrencyFormat()
    {
    }

    /**
     * Test attribute "iso_code"
     */
    public function testPropertyIsoCode()
    {
    }

    /**
     * Test attribute "example_format"
     */
    public function testPropertyExampleFormat()
    {
    }

    /**
     * Test attribute "decimal_digits"
     */
    public function testPropertyDecimalDigits()
    {
    }

    /**
     * Test attribute "decimal_separator"
     */
    public function testPropertyDecimalSeparator()
    {
    }

    /**
     * Test attribute "symbol_first"
     */
    public function testPropertySymbolFirst()
    {
    }

    /**
     * Test attribute "group_separator"
     */
    public function testPropertyGroupSeparator()
    {
    }

    /**
     * Test attribute "currency_symbol"
     */
    public function testPropertyCurrencySymbol()
    {
    }

    /**
     * Test attribute "display_symbol"
     */
    public function testPropertyDisplaySymbol()
    {
    }
}
