<?php
/**
 * MonthSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YNAB;

use PHPUnit\Framework\TestCase;

/**
 * MonthSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description MonthSummary
 * @package     YNAB
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MonthSummaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MonthSummary"
     */
    public function testMonthSummary()
    {
    }

    /**
     * Test attribute "month"
     */
    public function testPropertyMonth()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "income"
     */
    public function testPropertyIncome()
    {
    }

    /**
     * Test attribute "budgeted"
     */
    public function testPropertyBudgeted()
    {
    }

    /**
     * Test attribute "activity"
     */
    public function testPropertyActivity()
    {
    }

    /**
     * Test attribute "to_be_budgeted"
     */
    public function testPropertyToBeBudgeted()
    {
    }

    /**
     * Test attribute "age_of_money"
     */
    public function testPropertyAgeOfMoney()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }
}
