<?php
/**
 * TransactionSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YNAB;

use PHPUnit\Framework\TestCase;

/**
 * TransactionSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description TransactionSummary
 * @package     YNAB
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionSummaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TransactionSummary"
     */
    public function testTransactionSummary()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
    }

    /**
     * Test attribute "cleared"
     */
    public function testPropertyCleared()
    {
    }

    /**
     * Test attribute "approved"
     */
    public function testPropertyApproved()
    {
    }

    /**
     * Test attribute "flag_color"
     */
    public function testPropertyFlagColor()
    {
    }

    /**
     * Test attribute "flag_name"
     */
    public function testPropertyFlagName()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "payee_id"
     */
    public function testPropertyPayeeId()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "transfer_account_id"
     */
    public function testPropertyTransferAccountId()
    {
    }

    /**
     * Test attribute "transfer_transaction_id"
     */
    public function testPropertyTransferTransactionId()
    {
    }

    /**
     * Test attribute "matched_transaction_id"
     */
    public function testPropertyMatchedTransactionId()
    {
    }

    /**
     * Test attribute "import_id"
     */
    public function testPropertyImportId()
    {
    }

    /**
     * Test attribute "import_payee_name"
     */
    public function testPropertyImportPayeeName()
    {
    }

    /**
     * Test attribute "import_payee_name_original"
     */
    public function testPropertyImportPayeeNameOriginal()
    {
    }

    /**
     * Test attribute "debt_transaction_type"
     */
    public function testPropertyDebtTransactionType()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }
}
