<?php
/**
 * BudgetsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace YNAB;

use YNAB\Configuration;
use YNAB\ApiException;
use YNAB\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BudgetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BudgetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getBudgetById
     *
     * Single budget.
     *
     */
    public function testGetBudgetById()
    {
    }

    /**
     * Test case for getBudgetSettingsById
     *
     * Budget Settings.
     *
     */
    public function testGetBudgetSettingsById()
    {
    }

    /**
     * Test case for getBudgets
     *
     * List budgets.
     *
     */
    public function testGetBudgets()
    {
    }
}
