<?php
/**
 * TransactionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * OpenAPI spec version: 1.72.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace YNAB;

use YNAB\Configuration;
use YNAB\ApiException;
use YNAB\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  YNAB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTransaction
     *
     * Create a single transaction or multiple transactions.
     *
     */
    public function testCreateTransaction()
    {
    }

    /**
     * Test case for deleteTransaction
     *
     * Deletes an existing transaction.
     *
     */
    public function testDeleteTransaction()
    {
    }

    /**
     * Test case for getTransactionById
     *
     * Single transaction.
     *
     */
    public function testGetTransactionById()
    {
    }

    /**
     * Test case for getTransactions
     *
     * List transactions.
     *
     */
    public function testGetTransactions()
    {
    }

    /**
     * Test case for getTransactionsByAccount
     *
     * List account transactions.
     *
     */
    public function testGetTransactionsByAccount()
    {
    }

    /**
     * Test case for getTransactionsByCategory
     *
     * List category transactions, excluding any pending transactions.
     *
     */
    public function testGetTransactionsByCategory()
    {
    }

    /**
     * Test case for getTransactionsByMonth
     *
     * List transactions in month, excluding any pending transactions.
     *
     */
    public function testGetTransactionsByMonth()
    {
    }

    /**
     * Test case for getTransactionsByPayee
     *
     * List payee transactions, excluding any pending transactions.
     *
     */
    public function testGetTransactionsByPayee()
    {
    }

    /**
     * Test case for importTransactions
     *
     * Import transactions.
     *
     */
    public function testImportTransactions()
    {
    }

    /**
     * Test case for updateTransaction
     *
     * Updates an existing transaction.
     *
     */
    public function testUpdateTransaction()
    {
    }

    /**
     * Test case for updateTransactions
     *
     * Update multiple transactions.
     *
     */
    public function testUpdateTransactions()
    {
    }
}
